name: ptnsupplier
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  shared_preferences: ^2.5.1
  toggle_switch: ^2.3.0
  intl: ^0.20.2
  date_time_format: ^2.0.1
  rflutter_alert: ^2.0.7   #request to change
  loader_overlay: ^5.0.0
  loading_animation_widget: ^1.3.0
  image: ^4.5.4
  image_picker: ^1.1.2
  webview_flutter: ^4.13.0
  font_awesome_flutter: ^10.8.0
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  syncfusion_flutter_datepicker: ^32.1.22
  flutter_date_range_picker: ^0.2.1
  flutter_picker_plus: ^1.5.2
  awesome_dialog: ^3.2.1



  # loading: ^1.0.2
  loadmore: ^2.0.1


  # flutter_webview_plugin: ^0.4.0
  # barcode_scan: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/logo_master.png
    - images/shopping_cart.png
    - images/icon_logout.png
    - images/icon_losesale.png
    - images/icon_outofstock.png
    - images/icon_overstock.png
    - images/icon_overstock3.png
    - images/icon_drugs.png
    - images/1-angry.png
    - images/2-sad.png
    - images/3-ok.png
    - images/4-smile.png
    - images/icon_googlemap.jpg
    - images/icon_dealspacialprice.png
    - images/
  #  - images/a_dot_ham.jpeg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
